# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 884d6dc2a7b0e0124dab00f85793c51d3989f91f88c9623cac71e29c42e58ee8b5f57d208557a7b4f72cec0001bbe9bafcf6a2faa25823559bcdf235447e5b37
  aws_access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: f675ac5d50cf8ac828511cf3bc003e7559a1f746a6de02543ff5cfd13d64e190b3b6236b232ce81361b94397b0c2055be1aa0914dadec8fd423ea5e5bf9b5136

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"] %>
